"""
Pydantic data models shared across the API layer.

These models define the "contract" between frontend and backend: what a
request must contain, and what shape a response will have. Keeping them
in one place makes the OpenAPI/Swagger docs (auto-generated by FastAPI)
accurate and easy to browse at /docs.
"""
from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, confloat


class LatLng(BaseModel):
    """A single WGS84 coordinate pair."""
    lat: confloat(ge=-90, le=90) = Field(..., description="Latitude in decimal degrees")
    lng: confloat(ge=-180, le=180) = Field(..., description="Longitude in decimal degrees")


class Stop(BaseModel):
    """
    A delivery stop (or the depot). `id` is a client-generated identifier
    (e.g. a UUID or incrementing index) so the frontend can match the
    optimized order back to its own markers.
    """
    id: str = Field(..., description="Client-side identifier for this stop")
    label: Optional[str] = Field(None, description="Human readable label / address")
    location: LatLng
    service_time_minutes: float = Field(
        5.0, ge=0, description="Time spent at this stop (loading/unloading), in minutes"
    )
    priority: int = Field(0, description="Higher = more urgent (reserved for future VRP use)")
    time_window_start: Optional[str] = Field(None, description="ISO time, e.g. '09:00' (future use)")
    time_window_end: Optional[str] = Field(None, description="ISO time, e.g. '17:00' (future use)")


class RouteEndStrategy(str, Enum):
    RETURN_TO_DEPOT = "return_to_depot"
    END_AT_LAST_STOP = "end_at_last_stop"


class OptimizeRequest(BaseModel):
    depot: Stop = Field(..., description="Starting (and optionally ending) location")
    stops: List[Stop] = Field(..., min_items=1, description="Delivery stops to visit")
    end_strategy: RouteEndStrategy = RouteEndStrategy.RETURN_TO_DEPOT
    departure_time: Optional[str] = Field(
        None, description="ISO 8601 departure datetime, used to compute ETAs"
    )
    time_limit_seconds: int = Field(
        10, ge=1, le=120, description="Max seconds OR-Tools may spend searching for a solution"
    )
    osrm_base_url: Optional[str] = Field(
        None, description="Override the default public OSRM server, e.g. a self-hosted instance"
    )


class GeocodeRequest(BaseModel):
    query: str = Field(..., min_length=2, description="Free-text address, e.g. '221B Baker Street'")
    limit: int = Field(5, ge=1, le=10)


class GeocodeResult(BaseModel):
    display_name: str
    location: LatLng
    place_id: Optional[str] = None
    importance: Optional[float] = None


class DistanceMatrixRequest(BaseModel):
    locations: List[LatLng] = Field(..., min_items=2)
    osrm_base_url: Optional[str] = None


class DistanceMatrixResponse(BaseModel):
    distances_m: List[List[float]] = Field(..., description="Meters, [from][to]")
    durations_s: List[List[float]] = Field(..., description="Seconds, [from][to]")


class RouteGeometryRequest(BaseModel):
    ordered_locations: List[LatLng] = Field(..., min_items=2)
    osrm_base_url: Optional[str] = None


class RouteGeometryResponse(BaseModel):
    geometry: List[LatLng] = Field(..., description="Polyline as a list of lat/lng points")
    distance_m: float
    duration_s: float


class OptimizedStop(BaseModel):
    stop: Stop
    sequence_index: int
    leg_distance_m: float
    leg_duration_s: float
    cumulative_distance_m: float
    cumulative_duration_s: float
    estimated_arrival: Optional[str] = None


class RouteStatistics(BaseModel):
    total_distance_m: float
    total_duration_s: float
    num_stops: int
    average_stop_service_minutes: float
    estimated_completion_time: Optional[str] = None
    naive_total_duration_s: float
    time_saved_s: float
    time_saved_percent: float
    route_efficiency_score: float = Field(
        ..., description="0-100 score: how close to theoretical best vs naive ordering"
    )
    estimated_fuel_liters: float
    estimated_fuel_cost: float
    estimated_co2_kg: float


class OptimizeResponse(BaseModel):
    ordered_stops: List[OptimizedStop]
    geometry: List[LatLng]
    statistics: RouteStatistics
    solver_status: str
    algorithm: str = "OR-Tools: PATH_CHEAPEST_ARC + Guided Local Search"
